Rookie.CustomerSite/Models/ErrorViewModel.cs
using System;

namespace Rookie.CustomerSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Rookie.CustomerSite/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Rookie.CustomerSite.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult SignIn()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, "oidc");
        }

        public new IActionResult SignOut()
        {
            return SignOut(new AuthenticationProperties { RedirectUri = "/" }, "Cookies", "oidc");
        }

        [Authorize]
        public ActionResult MyProfile()
        {
            return View();
        }
    }
}

Rookie.CustomerSite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rookie.CustomerSite.Interfaces;
using Rookie.CustomerSite.Models;
using RookieShop.Shared.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Rookie.CustomerSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        public HomeController(ILogger<HomeController> logger, IProductService productService, ICategoryService categoryService)
        {
            _logger = logger;
            _productService = productService;
            _categoryService = categoryService;


        }

        public async Task<IActionResult> Index(int? CategoryID, string name)
        {
            ViewData["CurrentFilter"] = name;
            var homeVM = new HomeVM();
            if (!CategoryID.HasValue) {
                var homeVM1 = new HomeVM
                {
                    Products = await _productService.GetProductAsync(),
                    Categories = await _categoryService.GetCategoryAsync()
                };
                homeVM = homeVM1;
            }           
            else
            {
                var homeVM1 = new HomeVM
                {
                    Products = await _productService.GetProductByCategory(CategoryID.Value),                    
                    Categories = await _categoryService.GetCategoryAsync()
                };
                
                homeVM = homeVM1;
            }
            if (!String.IsNullOrEmpty(name))
            {
                var homeVM1 = new HomeVM
                {
                    Products = await _productService.SearchProduct(name),
                    Categories = await _categoryService.GetCategoryAsync()
                };
                homeVM = homeVM1;
            }

            return View(homeVM);
        }
        public async Task<IActionResult> ViewProductByCategory(int? productID)
        {
            var homeVM = new HomeVM
            {
                Products = await _productService.GetProductByCategory(productID.Value),
                Categories = await _categoryService.GetCategoryAsync()
            };
            return View(homeVM);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rookie.CustomerSite/Controllers/ProductDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Rookie.CustomerSite.Interfaces;
using Rookie.CustomerSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using RookieShop.Shared.ViewModels;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using RookieShop.Shared.DTOs.ProductReviewDTO;

namespace Rookie.CustomerSite.Controllers
{
    
    public class ProductDetailController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProductReviewService _productReviewService;
        public ProductDetailController(IProductService productService, IProductReviewService productreviewService)
        {
            _productService = productService;
            _productReviewService = productreviewService; 
        }
        /*public IActionResult Index()
        {
            return View();
        }*/
        public async Task<IActionResult> Index(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var productDetailVM = new ProductDetailVM
            {
                Product = await _productService.GetProductByIdAsync(Id.Value),
                Reviews = await _productReviewService.GetProductReviewAsync(Id.Value)
            };
            
            return View(productDetailVM);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> PostReview(string userName, int rating, string comment, int productId)
        {
            var review = new ProductReviewRequest
            {
                UserName = userName,
                Rating = rating,
                Comment = comment,
                ProductId = productId,
            };
            await _productReviewService.PostReview(review);
            return RedirectToAction("Index", new { Id = productId });
        }
    }
}

Rookie.CustomerSite/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Rookie.CustomerSite.Services;
using Rookie.CustomerSite.Interfaces;
using RookieShop.Shared.ViewModels;

namespace Rookie.CustomerSite.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var VM = new CategoryVCVM
            {
                Categories = await _categoryService.GetCategoryAsync()
            };
            
            return View(VM);
        }
    }
}

Rookie.CustomerSite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using RookieShop.Shared.ViewModels
@model HomeVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="row">
    
    <form asp-action="Index" method="POST" class="search_form span6">
        <input type="text" name="name" value="@ViewData["CurrentFilter"]" class="input-block-level search-query" style="color: black; margin: 0 auto;"; Placeholder="Nhập thứ bạn cần tìm . . .">
        <input type="submit" style="color:black"; value="Search" class="btn btn-default "/>
    </form>
</div>
    <div  class="text-center col-12">
        <h1 class="display-4">Welcome to ROOKIESHOP</h1>
        
    </div>

    <section class="main-content">

        <div class="row">
            <div class="span9">
                <ul class="thumbnails listing-products">
                    @foreach (var item in Model.Products)
                    {
                        <li class="span3">
                            <div class="product-box">

                                <span class="sale_tag"></span>
                                <a asp-controller="ProductDetail" asp-action="Index" asp-route-id=@item.Id><img alt="" src="~/images/ladies/1.jpg"></a><br />
                                <a asp-controller="ProductDetail" asp-action="Index" asp-route-id=@item.Id class="title">@item.ProductName</a><br />
                                <a href="#" class="category">@item.CategoryName</a>
                                <p class="price">$@item.Price</p>
                            </div>
                        </li>
                    }
                    </ul>
                </div>
                @await Component.InvokeAsync("CategoryList")
            </div>
        </section>

Rookie.CustomerSite/Views/ProductDetail/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using RookieShop.Shared.ViewModels
@model ProductDetailVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

    <section class="header_text sub">
        <h4><span>@Model.Product.ProductName</span></h4>
    </section>
    <section class="main-content">
        <div class="row">
            <div class="span9">
                <div class="row">
                    <div class="span4">
                        <a href="~/images/ladies/1.jpg" class="thumbnail" data-fancybox-group="group1" title="Description 1"><img alt="" src="~/images/ladies/1.jpg"></a>
                    </div>
                    <div class="span5">
                        <address>
                            <strong>Category:</strong> <span>@Model.Product.CategoryName</span><br>
                            <strong>Product Code:</strong> <span>@Model.Product.Id</span><br>
                            <strong>Reward Points:</strong> <span>0</span><br>
                            <strong>Availability:</strong> <span>@Model.Product.Quantity</span><br>
                        </address>
                        <h4><strong>@Model.Product.Price</strong></h4>
                    </div>
                    <div class="span5">
                        <form class="form-inline">
                            <label class="checkbox">
                                <input type="checkbox" value=""> Option one is this and that
                            </label>
                            <br />
                            <label class="checkbox">
                                <input type="checkbox" value=""> Be sure to include why it's great
                            </label>
                            <p>&nbsp;</p>
                            <label>Số lượng:</label>
                            <input type="text" class="span1" placeholder="1">
                            <button class="btn btn-inverse" type="submit">Add to cart</button>
                        </form>

                        <div>
                            @for (var i = 1; i <= Model.Product.Rating; i++)
                            {
                                <span class="starGlowN"></span>
                            }
                            @for (var i = (Model.Product.Rating + 1); i <= 5; i++)
                            {
                                <span class="starFadeN"></span>
                            }
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="span9">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class="active"><a href="#home">Description</a></li>
                            <li class=""><a href="#profile">Additional Information</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="home">@Model.Product.Description</div>
                            <div class="tab-pane" id="profile">
                                <table class="table table-striped shop_attributes">
                                    <tbody>
                                        @foreach (var cmt in Model.Reviews)
                                        {
                                            <tr class="">
                                                <th>@cmt.UserName</th>
                                                <td>@cmt.Comment</td>
                                            </tr>

                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                @if (User.Identity.IsAuthenticated)
                {
                    <form class="join" asp-action="PostReview" asp-controller="ProductDetail" method="post">
                        <input type="text" id="usname" name="userName" value="" placeholder="Name"  class="form-control" />
                        <input type="hidden" id="prdId" name="productId" value="@Model.Product.Id"/>
                        <div onmouseout="CRateSelected()">
                            <span class="starFade" id="Rate1" onclick="CRate(1)" onmouseover="CRateOver(1)" onmouseout="CRateOut(1)"></span><span class="starFade" id="Rate2" onclick="CRate(2)" onmouseover="CRateOver(2)" onmouseout="CRateOut(2)"></span><span class="starFade" id="Rate3" onclick="CRate(3)" onmouseover="CRateOver(3)" onmouseout="CRateOut(3)"></span><span class="starFade" id="Rate4" onclick="CRate(4)" onmouseover="CRateOver(4)" onmouseout="CRateOut(4)"></span><span class="starFade" id="Rate5" onclick="CRate(5)" onmouseover="CRateOver(5)" onmouseout="CRateOut(5)"></span>
                            <input type="hidden" name="rating" id="Rating" value="0" />
                        </div>
                        <div class="col-md-12">
                            <textarea name="comment" id="Comment" required rows="5" style="width:100%;" class="form-control"></textarea>
                        </div>
                        <button onclick="checkifwork()" class="btn btn btn-success flex-shrink-0 form-control" type ="submit">Thêm bình luận</button>
                    </form>
                }

                </div>
        </div>
    </section>
    <script src="~/js/common.js"></script>
    <script>
        $(function () {
            $('#myTab a:first').tab('show');
            $('#myTab a').click(function (e) {
                e.preventDefault();
                $(this).tab('show');
            })
        })
        $(document).ready(function () {
            $('.thumbnail').fancybox({
                openEffect: 'none',
                closeEffect: 'none'
            });

            $('#myCarousel-2').carousel({
                interval: 2500
            });
        });
        function SCRate() {
        for (var i = 1; i <= @Model.Product.Rating ; i++) {
            $("#sRate" + i).attr('class', 'starGlowN');
        }
    }
    $(function(){
        SCRate();
    });
        function SubmitComment() {
            if ($("#Rating").val() == "0") {
                alert("Please rate this service provider.");
                return false;
            }
            else {
                return true;
            }
        }
        function CRate(r) {
            $("#Rating").val(r);            
            for (var i = 1; i <= r; i++) {
                $("#Rate" + i).attr('class', 'starGlow');
                
            }
            // unselect remaining
            for (var i = r + 1; i <= 5; i++) {
                $("#Rate" + i).attr('class', 'starFade');
                
            }
        }
        function checkifwork()
        {
            console.log($("#usname").val());
            console.log($("#prdId").val());

            console.log($("#Rating").val());
            console.log($("#Comment").val());

        }
        function CRateOver(r) {
            for (var i = 1; i <= r; i++) {
                $("#Rate" + i).attr('class', 'starGlow');
            }
        }
        function CRateOut(r) {
            for (var i = 1; i <= r; i++) {
                $("#Rate" + i).attr('class', 'starFade');
            }
        }
        function CRateSelected() {
            var setRating = $("#Rating").val();
            for (var i = 1; i <= setRating; i++) {
                $("#Rate" + i).attr('class', 'starGlow');
            }
        }
    </script>

Rookie.CustomerSite/Views/Shared/Components/CategoryList/Default.cshtml
@using RookieShop.Shared.ViewModels;
@using RookieShop.Shared.DTOs
@model CategoryVCVM
<div class="span3 col">
    <div class="block">
        <ul class="nav nav-list">
            <li class="nav-header"><h4 class="title text-center"><strong>Danh mục sản phẩm</strong></h4></li>
            @foreach (var item in Model.Categories)
            {
                <li>
                    <a asp-controller="Home" asp-action="Index" asp-route-CategoryId="@item.Id">@item.CategoryName</a>
                </li>
            }
        </ul>
        
     </div>
</div>

Rookie.CustomerSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="">
    <title>@ViewData["Title"] - Rookie.CustomerSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bootstrappage.css" />
    <link rel="stylesheet" href="~/css/flexslider.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/css/jquery.fancybox.css" />
    <script src="~/js/jquery-1.7.2.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/superfish.js"></script>
    <script src="~/js/jquery.scrolltotop.js"></script>
    <script src="~/js/jquery.fancybox.js"></script>



</head>
<body>
    <div id="top-bar" class="container">
        <div class="row">
            <div class="span4">
                <form method="POST" class="search_form">
                    <input type="text" class="input-block-level search-query" Placeholder="eg. T-sirt">
                </form>
            </div>
            <div class="span8">
                <div class="account pull-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="user-menu">
                            <li><a asp-controller="Account" asp-action="MyProfile">Hello @User.Identity.Name !</a></li>
                            <li><a href="cart.html">Your Cart</a></li>
                            <li><a href="checkout.html">Checkout</a></li>
                            <li><a asp-controller="Account" asp-action="SignOut">Logout</a></li>
                        </ul>
                        
                    }
                    else
                    {
                        <ul class="user-menu">
                            <li><a asp-controller="Account" asp-action="SignIn">Login</a></li>
                        </ul>
                    }
                </div>
            </div>
        </div>
    </div>
    <div id="wrapper" class="container">
        <section class="navbar main-menu">
            <div class="navbar-inner main-menu">
                <a class="logo pull-left" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" class="site_logo" alt=""></a>
                <nav id="menu" class="pull-right">
                    <ul>
                        <li>
                            <a href="./products.html">Woman</a>
                            <ul>
                                <li><a href="./products.html">Lacinia nibh</a></li>
                                <li><a href="./products.html">Eget molestie</a></li>
                                <li><a href="./products.html">Varius purus</a></li>
                            </ul>
                        </li>
                        <li><a href="./products.html">Man</a></li>
                        <li>
                            <a href="./products.html">Sport</a>
                            <ul>
                                <li><a href="./products.html">Gifts and Tech</a></li>
                                <li><a href="./products.html">Ties and Hats</a></li>
                                <li><a href="./products.html">Cold Weather</a></li>
                            </ul>
                        </li>
                        <li><a href="./products.html">Hangbag</a></li>
                        <li><a href="./products.html">Best Seller</a></li>
                        <li><a href="./products.html">Top Seller</a></li>
                    </ul>
                </nav>
            </div>
        </section>


        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Rookie.CustomerSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
</body>
</html>